[package]
name = "wut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redux-rs = "0.3.3"
tokio = { version = "1.41.1", features = ["full"] }

[lib]
name = "wut"
path = "src/main.rs"
